[colors.primary]
background = '#100f0f'
foreground = '#cecdc3'

[colors.selection]
text = '#cecdc3'
background = '#205ea6'

[colors.cursor]
text = '#100f0f'
cursor = '#879a39'

[colors.normal]
black   = '#100F0F'
red     = '#cd604c'
green   = '#429a38'
yellow  = '#c0ad3b'
blue    = '#7c9223'
magenta = '#394700'
cyan    = '#879A39'
white   = '#9fa195'

[colors.bright]
black   = '#77796f'
red     = '#cf7b6d'
green   = '#6fb867'
yellow  = '#e6d881'
blue    = '#97a94e'
magenta = '#b6c86f'
cyan    = '#cbd79a'
white   = '#dddfd8'
