#!/usr/bin/perl

# File generated by menutray v0.50

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit '/home/rick/.config/menutray/schema.pl' instead!

use utf8;
use strict;
use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

$icon->set_from_icon_name('start-here');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

load_menu();

sub show_icon_menu {
    $menu->popup(undef, undef, sub {return Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon)}, [1, 1], 0, 0);
    return 1;
}

sub load_menu {

    $menu->append('Gtk2::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Development");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Android\ File\ Manager");
    $app->signal_connect('activate', sub {system "aafm &"});
    $app->set_property('tooltip_text', "A\ file\ manager\ for\ Android\ devices\,\ using\ the\ official\ SDK\'s\ ADB\ utility\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("aafm",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Android\ Studio");
    $app->signal_connect('activate', sub {system "android\-studio &"});
    $app->set_property('tooltip_text', "The\ official\ Android\ IDE");
    $app->set_image('Gtk2::Image'->new_from_icon_name("android\-studio",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Code\:\:Blocks");
    $app->signal_connect('activate', sub {system "env\ GTK2_RC_FILES\=\/home\/rick\/\.themes\/IcyBlack\/gtk\-2\.0\/gtkrc\ codeblocks &"});
    $app->set_property('tooltip_text', "Configurable\ and\ extensible\ IDE");
    $app->set_image('Gtk2::Image'->new_from_icon_name("codeblocks",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Electron");
    $app->signal_connect('activate', sub {system "electron &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("electron",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Git\ Cola");
    $app->signal_connect('activate', sub {system "git\-cola\ \-\-prompt &"});
    $app->set_property('tooltip_text', "The\ highly\ caffeinated\ Git\ GUI");
    $app->set_image('Gtk2::Image'->new_from_icon_name("git\-cola",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Heimdall");
    $app->signal_connect('activate', sub {system "heimdall\-frontend &"});
    $app->set_property('tooltip_text', "Samsung\ Galaxy\ Firmware\ Flasher");
    $app->set_image('Gtk2::Image'->new_from_icon_name("heimdall",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("HexEditor");
    $app->signal_connect('activate', sub {system "wxHexEditor &"});
    $app->set_property('tooltip_text', "A\ hex\ editor\ for\ huge\ files\ and\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("wxHexEditor",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("JD\-GUI");
    $app->signal_connect('activate', sub {system "env\ _JAVA_OPTIONS\=\'\-Dawt\.useSystemAAFontSettings\=on\ \-Dswing\.aatext\=true\ \-Dswing\.defaultlaf\=com\.sun\.java\.swing\.plaf\.gtk\.GTKLookAndFeel\'\ jd\-gui &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("env",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Meld");
    $app->signal_connect('activate', sub {system "meld &"});
    $app->set_property('tooltip_text', "Compare\ and\ merge\ your\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("meld",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Neovim");
    $app->signal_connect('activate', sub {system "termite\ \-\-geometry\=1200x800\ \-e\ nvim &"});
    $app->set_property('tooltip_text', "Edit\ text\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("nvim",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Raccoon");
    $app->signal_connect('activate', sub {system "raccoon &"});
    $app->set_property('tooltip_text', "Alternative\ Google\ Play\ client\ to\ download\ Android\ APK\ files\ to\ your\ computer");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/raccoon\.svg",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sublime\ Text");
    $app->signal_connect('activate', sub {system "subl3 &"});
    $app->set_property('tooltip_text', "Sophisticated\ text\ editor\ for\ code\,\ markup\ and\ prose");
    $app->set_image('Gtk2::Image'->new_from_icon_name("sublime\-text",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SuperR\'s\ Kitchen");
    $app->signal_connect('activate', sub {system "\ termite\ \-\-hold\ \-e\ \/home\/rick\/superrs\-kitchen\/superr &"});
    $app->set_image('Gtk2::Image'->new_from_stock(q{gtk-missing-image},q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # EDUCATION # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Education");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-science",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Klavaro");
    $app->signal_connect('activate', sub {system "klavaro &"});
    $app->set_property('tooltip_text', "A\ very\ flexible\ and\ efficient\ touch\ typing\ tutor\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("klavaro",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Graphics");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Gimp");
    $app->signal_connect('activate', sub {system "gimp\-2\.8 &"});
    $app->set_property('tooltip_text', "Create\ images\ and\ edit\ photographs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gimp",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Inkscape");
    $app->signal_connect('activate', sub {system "inkscape &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ Scalable\ Vector\ Graphics\ images");
    $app->set_image('Gtk2::Image'->new_from_icon_name("inkscape",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Multimedia");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Clementine");
    $app->signal_connect('activate', sub {system "clementine &"});
    $app->set_property('tooltip_text', "Plays\ music\ and\ last\.fm\ streams");
    $app->set_image('Gtk2::Image'->new_from_icon_name("clementine",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("easyMP3Gain");
    $app->signal_connect('activate', sub {system "easymp3gain &"});
    $app->set_property('tooltip_text', "A\ GUI\ for\ mp3gain\,\ vorbisgain\ and\ aacgain");
    $app->set_image('Gtk2::Image'->new_from_icon_name("easymp3gain",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("mpv\ Media\ Player");
    $app->signal_connect('activate', sub {system "mpv\ \-\-player\-operation\-mode\=pseudo\-gui\ \-\- &"});
    $app->set_property('tooltip_text', "Play\ movies\ and\ songs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mpv",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("MusicBrainz\ Picard");
    $app->signal_connect('activate', sub {system "picard &"});
    $app->set_property('tooltip_text', "Tag\ your\ music\ with\ the\ next\ generation\ MusicBrainz\ tagger");
    $app->set_image('Gtk2::Image'->new_from_icon_name("picard",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("VDrumLib");
    $app->signal_connect('activate', sub {system "wine\ \~\/\.wine\/drive_c\/Program\\\ Files\\\ \\\(x86\\\)\/VDrumLib\/v231\\\/VDrumLib\.exe &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("wine",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Network");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Chromium");
    $app->signal_connect('activate', sub {system "chromium &"});
    $app->set_property('tooltip_text', "Access\ the\ Internet");
    $app->set_image('Gtk2::Image'->new_from_icon_name("chromium",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Skype");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/skypeforlinux &"});
    $app->set_property('tooltip_text', "Skype\ Internet\ Telephony");
    $app->set_image('Gtk2::Image'->new_from_icon_name("skypeforlinux",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SoulSeek");
    $app->signal_connect('activate', sub {system "soulseekqt &"});
    $app->set_property('tooltip_text', "Soulseek\ music\-sharing\ client");
    $app->set_image('Gtk2::Image'->new_from_icon_name("soulseek",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Tor\-Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/tor\-browser\-en &"});
    $app->set_property('tooltip_text', "Tor\ Browser\ Bundle\:\ Anonymous\ browsing\ using\ firefox\ and\ tor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("tor\-browser\-en",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Transmission");
    $app->signal_connect('activate', sub {system "transmission\-gtk &"});
    $app->set_property('tooltip_text', "Download\ and\ share\ files\ over\ BitTorrent");
    $app->set_image('Gtk2::Image'->new_from_icon_name("transmission",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("LXAppearance");
    $app->signal_connect('activate', sub {system "lxappearance &"});
    $app->set_property('tooltip_text', "Customizes\ look\ and\ feel\ of\ your\ desktop\ and\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Openbox\ Configuration\ Manager");
    $app->signal_connect('activate', sub {system "obconf &"});
    $app->set_property('tooltip_text', "Tweak\ settings\ for\ Openbox");
    $app->set_image('Gtk2::Image'->new_from_icon_name("obconf",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Tint2\ Settings");
    $app->signal_connect('activate', sub {system "tint2conf &"});
    $app->set_property('tooltip_text', "Tool\ to\ configure\ the\ tint2\ panel");
    $app->set_image('Gtk2::Image'->new_from_icon_name("tint2conf",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("WpGTK");
    $app->signal_connect('activate', sub {system "env\ GTK2_RC_FILES\=\/usr\/share\/themes\/FlatStudioCustom\/gtk\-2\.0\/gtkrc\ wpg &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("env",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("System");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Archive\ Manager");
    $app->signal_connect('activate', sub {system "file\-roller &"});
    $app->set_property('tooltip_text', "Create\ and\ modify\ an\ archive");
    $app->set_image('Gtk2::Image'->new_from_icon_name("file\-roller",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("BleachBit");
    $app->signal_connect('activate', sub {system "bleachbit &"});
    $app->set_property('tooltip_text', "Free\ space\ and\ maintain\ privacy");
    $app->set_image('Gtk2::Image'->new_from_icon_name("bleachbit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Disks");
    $app->signal_connect('activate', sub {system "gnome\-disks &"});
    $app->set_property('tooltip_text', "Manage\ Drives\ and\ Media");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gnome\-disks",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GParted");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/gparted_polkit &"});
    $app->set_property('tooltip_text', "Create\,\ reorganize\,\ and\ delete\ partitions");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gparted",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Ranger");
    $app->signal_connect('activate', sub {system "termite\ \-\-geometry\=1200x800\ \-e\ ranger &"});
    $app->set_property('tooltip_text', "Launches\ the\ ranger\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sunflower");
    $app->signal_connect('activate', sub {system "sunflower &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system\ and\ manage\ the\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("sunflower",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Termite");
    $app->signal_connect('activate', sub {system "termite &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Tint2");
    $app->signal_connect('activate', sub {system "tint2 &"});
    $app->set_property('tooltip_text', "Lightweight\ panel");
    $app->set_image('Gtk2::Image'->new_from_icon_name("tint2",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("UNetbootin");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/unetbootin &"});
    $app->set_property('tooltip_text', "Tool\ for\ creating\ Live\ USB\ drives");
    $app->set_image('Gtk2::Image'->new_from_icon_name("unetbootin",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}
    $menu->show_all;
    return 1;
}
'Gtk2'->main;
