#! /bin/zsh

sxhkd &
xsetroot -cursor_name left_ptr &
setxkbmap -option ctrl:nocaps &


bspc monitor -d      
#bspc monitor -d 一 二 三 四 五
#bspc monitor -d term web files git chat music

bspc config border_width        2
bspc config window_gap          6

#bspc config border_radius       20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config click_to_focus true

# Border colors
bspc config normal_border_color "#636363"
bspc config focused_border_color "#E3C12C"
bspc config urgent_border_color "#C60000"

# rules
bspc desktop  -l monocle
bspc rule -a mpv state=floating
bspc rule -a mplayer state=floating border=off
bspc rule -a Tor Browser desktop='' follow=on
bspc rule -a Sunflower desktop=^3 follow=on
# bspc rule -a Meld desktop='chat' follow=on

bspc rule -a Gtick state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Obconf state=floating
bspc rule -a Arandr state=floating
bspc rule -a retroarch state=floating border=off
bspc rule -a File-roller state=floating
bspc rule -a GParted state=floating focus=on
bspc rule -a Wpg state=floating
bspc rule -a feh state=floating
bspc rule -a skypeforlinux state=floating
bspc rule -a Termite state=floating
bspc rule -a kitty state=floating
bspc rule -a Screenkey manage=off

# startups
termite --geometry=1100x700+408+43 &
polybar top &
# xscreensaver -no-splash &
xbanish &
~/.fehbg &
compton --config ~/.config/compton.conf -b &
# redshift &
# cadence --minimized &
[[ -z $(pgrep -xU $UID mpdscribble) ]] && mpdscribble &
mpd &
xcape -e 'Control_L=Escape' &
$HOME/.vim/bspwm_border_color/listener
# /usr/bin/xautolock -time 10 -locker /usr/bin/i3lock-fancy -detectsleep &

# bspc config external_rules_command ~/.config/bspwm/external-rules.sh
