#! /bin/zsh

sxhkd &
xsetroot -cursor_name left_ptr &
setxkbmap -option ctrl:nocaps &

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 一 二 三 四 五
bspc monitor -d code web files git chat music

bspc config border_width        3
bspc config window_gap          8

bspc config border_radius       20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config border_radius 5
# bspc config click_to_focus true

bspc config normal_border_color         "#6B4E5F"
bspc config focused_border_color        "#f1f1f1"
bspc config presel_feedback_color       "#A6A6A6"

# rules
bspc desktop web -l monocle
bspc rule -a mpv state=floating
bspc rule -a Tor Browser desktop='web' follow=on
bspc rule -a Sunflower desktop=^3 follow=on
bspc rule -a Meld desktop='chat' follow=on

bspc rule -a Gimp state=floating
bspc rule -a /home/rick/scripts/pennywise state=floating border=off
bspc rule -a Lxappearance state=floating
bspc rule -a Obconf state=floating
bspc rule -a arandr state=floating
bspc rule -a retroarch state=floating border=off
bspc rule -a File-roller state=floating
bspc rule -a GParted state=floating focus=on
bspc rule -a Oblogout state=floating
bspc rule -a Wpg state=floating
bspc rule -a feh state=floating
bspc rule -a skypeforlinux state=floating
bspc rule -a Termite state=floating
bspc rule -a kitty state=floating
bspc rule -a Screenkey manage=off

# startups\
kitty -o initial_window_width=1100 -o initial_window_height=700 &
#termite --geometry=1100x700+408+43 &
polybar top &
xbanish &
# ~/.config/wpg/wp_init.sh &
~/.fehbg &
#paramano &
compton --config ~/.config/compton.conf -b &
redshift &
mpd &
xcape -e 'Control_L=Escape' &
xinput disable 'SynPS/2 Synaptics TouchPad' &

bspc config external_rules_command ~/.config/bspwm/external-rules.sh
