#! /bin/zsh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config click_to_focus true
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_corner



bspc config active_border_color '#437BA2'
bspc config normal_border_color '#24556D'
bspc config focused_border_color '#77CEBC'

# startups
polybar top &!
~/.wallpapers/wp_init.sh &
compton --config /home/rick/.config/compton.conf -b &
redshift &

#bspc config top_padding 20
