reporting: "off"
os:
  openCommand: 'sh -c "xdg-open {{filename}} >/dev/null"'
gui:
  scrollHeight: 2
  theme:
    activeBorderColor:
      - red
      - magenta
    inactiveBorderColor:
      - blue
    optionsTextColor:
      - red
  commitLength:
    show: true