cursor #cecdc3
cursor_text_color #cecdc3

foreground            #cecdc3
background            #100f0f
selection_foreground  #100f0f
selection_background  #3aa99f
url_color             #3aa99f

color0   #100F0F
color1   #c56837
color2   #39a942
color3   #d3c73a
color4   #22a095
color5   #004e47
color6   #3AA99F
color7   #a3b1b0
color8   #707a79
color9   #e49b73
color10  #6dca74
color11  #fdf488
color12  #52b9b0
color13  #76dbd2
color14  #a6ece6
color15  #edf5f4
