cursor #cecdc3
cursor_text_color #cecdc3

foreground            #cecdc3
background            #100f0f
selection_foreground  #100f0f
selection_background  #d0a215
url_color             #d0a215

color0   #100F0F
color1   #fa290e
color2   #2fd015
color3   #ffd502
color4   #c59400
color5   #604800
color6   #D0A215
color7   #dad4c2
color8   #878274
color9   #ff6253
color10  #72f95c
color11  #ffe45e
color12  #e4b935
color13  #ffd75e
color14  #ffe597
color15  #fffcf3
