#!/bin/sh

init() {
    # Download folder
    path="/mnt/Movies&TV/YT-Downloads"

    # Channel URLs
    channels[bloxsy]="https://www.youtube.com/@bloxsy_"
    channels[guitar aerobics]="https://www.youtube.com/playlist?list=PLpxkNwUwbnTd0zbHIF6PHklTs5ympQWmZ"
    # ...
}

channels() {
    for name in "${!channels[@]}"; do
        channel "$name"
    done
}

channel() {
    name="$1"
    cd "$path"; mkdir -p "$name"; cd "$name"
    yt-dlp --download-archive archive.txt --write-info-json --force-ipv4 ${channels["$name"]}
    mkdir -p info; mv *.json info
}

declare -A channels
init
arguments=("channels" "channel")
[[ "${arguments[@]}" =~ "${1}" ]] && "$1" "$2"