#!/bin/bash

fastboot flash boot_a boot.img
fastboot flash boot_b boot.img
fastboot flash dtbo_a dtbo.img
fastboot flash dtbo_b dtbo.img
fastboot flash odm_a odm.img
fastboot flash odm_b odm.img
fastboot flash system_a system.img
fastboot flash system_b system.img
fastboot flash vbmeta_a vbmeta.img
fastboot flash vbmeta_b vbmeta.img
fastboot flash vendor_a vendor.img
fastboot flash vendor_b vendor.img
fastboot format:f2fs userdata
fastboot reboot



fastboot format:f2fs userdata
fastboot flash boot boot.img
fastboot flash dtbo dtbo.img
fastboot flash odm odm.img
fastboot flash system system.img
fastboot flash vbmeta vbmeta.img
fastboot flash vendor vendor.img
fastboot reboot