#!/bin/bash

cadence-session-start --system-start
sudo cpupower frequency-set --governor performance
bspc desktop --focus ^6 && env STAGING_RT_PRIORITY_SERVER=95 STAGING_RT_PRIORITY_BASE=15 chrt -f 50 "/opt/REAPER/reaper" %F