#!/bin/bash

echo "Setting CPU governor to PERFORMANCE..."
sudo cpupower frequency-set -g performance

echo "Launching Reaper..."
env WINE_RT=1 pw-jack reaper

# Return CPU to balanced schedutil
echo "Reaper closed. Returning CPU governor to schedutil..."
sudo cpupower frequency-set -g schedutil


