#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}
export TERMINAL='termite'
export WEB=chromium
export FILE=sunflower
hc emit_hook reload

# xsetroot -solid '#5A8E3A'
split_rate_h=${split_rate_h:-0.5}
resizestep_h=${resizestep_h:-0.005}
split_rate_v=${split_rate_v:-0.5}
resizestep_v=${resizestep_v:-0.02}

hc set tree_style '╾│ ├└╼─┐'

#---------------------------------------------------------------------------}}}
# Keybindings                                                               {{{
#------------------------------------------------------------------------------

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-c       close_or_remove
hc keybind $Mod-Shift-c remove
hc keybind $Mod-Return  spawn termite

# basic movement
# focusing clients
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-h focus left
hc keybind $Mod-l focus right
# cycle
hc keybind $Mod-Down cycle_all +1
hc keybind $Mod-Up   cycle_all -1

# moving clients
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-l shift right

# resizing frames
hc keybind $Mod-z      resize down  +$resizestep_v
hc keybind $Mod-a      resize up    +$resizestep_v
hc keybind $Mod-comma  resize left  +$resizestep_h
hc keybind $Mod-period resize right +$resizestep_h

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-s chain , split bottom $split_rate_h , focus down
hc keybind $Mod-v chain , split right  $split_rate_v , focus right
hc keybind $Mod-Control-j chain , split bottom 0.5 , focus down
hc keybind $Mod-Control-k chain , split top    0.5 , focus up
hc keybind $Mod-Control-h chain , split left   0.5 , focus left
hc keybind $Mod-Control-l chain , split right  0.5 , focus right
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode


# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible
# shift client to neighbor tag
hc keybind $Mod-Shift-Right move_index +1 --skip-visible
hc keybind $Mod-Shift-Left  move_index -1 --skip-visible

# layouting'
hc keybind $Mod-t  floating toggle
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-v fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize


# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

hc keybind $Mod-m spawn termite -e ncmpcpp
hc keybind $Mod-f spawn $FILE
hc keybind $Mod-w spawn $WEB

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#292F40'
#             ||
# panel color \/
hc set frame_border_normal_color '#40372B'
hc set frame_bg_normal_color '#292F40'
hc set frame_bg_active_color '#292F40'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap -1

# set seected 'window'and selected worksace throw its attr
hc attr theme.active.color '#FFDDAE'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#7F6F57'
hc attr theme.inner_width 2
hc attr theme.outer_width 2
hc attr theme.inner_color '#CCB18B'
hc attr theme.border_width 6
hc attr theme.floating.border_width 6
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color '#40372B'
hc attr theme.active.inner_color '#40372B'
hc attr theme.active.outer_color '#CCB18B'
hc attr theme.background_color '#CCB18B'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1

#---------------------------------------------------------------------------}}}
# Rules                                                                     {{{
#------------------------------------------------------------------------------

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class='Conky' manage=off

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class='conky' manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/home/rick/.config/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
~/.wallpapers/wp_init.sh  &
conky -c ~/.conky/conkyrc &
compton --config /home/rick/.config/compton.conf -b &
done
