#!/usr/bin/env bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

#autostart
#~/.wallpapers/wp_init.sh  &
~/.fehbg &
compton --config /home/rick/.config/compton.conf -b &
redshift &

hc emit_hook reload

# xrdb -cpp cpp -merge ~/.Xdefaults

killall lemons.sh

export TERMINAL=termite
export FILE=sunflower

hc set default_frame_layout 2

hc set frame_gap 0
hc set snap_gap 6
#xsetroot -solid '#5A8E3A'

hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-BackSpace quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn $TERMINAL
hc keybind $Mod-w spawn chromium
hc keybind $Mod-Shift-f spawn $FILE

# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# resizing frames
RESIZESTEP=0.04
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

#rofi
hc keybind $Mod-d spawn rofi -show run -width 25 -fg "#B0E670" -bg "#14161F" -hlfg "#14161F" -hlbg "#B0E670" -bc "#14161F" -location 0 -lines 4 -bw 0 -font "Dejavu Sans Mono 12" -opacity 90 -fuzzy -sidebar-mode -auto-select -regex -color-enabled -tokenize

# tags
tag_names=( 0000 0001 0010 0011 0100 )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "Control-$key" use_index "$i"
        hc keybind "$Mod-Control-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Escape use_previous

# layouting
hc keybind $Mod-i toggle always_show_frame
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-v split explode

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button3 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button1 resize
hc mousebind $Mod-B4 call substitute WID clients.dragged.winid spawn transset-df --inc -i WID 0.05
hc mousebind $Mod-B5 call substitute WID clients.dragged.winid spawn transset-df --dec -i WID -m 0.2 0.05
frame_gap_steps=( 0 1 2 3 $(seq 4 4 100) )
i=${#frame_gap_steps[@]} ; for x in "${frame_gap_steps[@]}" ; do reversed_frame_gap_steps[--i]=$x ; done
hc mousebind $Mod-Control-B4 call cycle_value frame_gap "${frame_gap_steps[@]}" "${reversed_frame_gap_steps[0]}"
hc mousebind $Mod-Control-B5 call cycle_value frame_gap "${reversed_frame_gap_steps[@]}" "${frame_gap_steps[0]}"

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c           cycle
hc keybind $Mod-i           jumpto urgent

hc set focus_follows_mouse 1
hc set raise_on_click 1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#849F31'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#222222'
hc set frame_bg_active_color '#101010'
hc set frame_border_width 2
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 1

hc attr theme.active.color '#66A3BF' #'#9fbc00'
hc attr theme.normal.color '#FFFFFF' #'#240054' #454545'
#hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#6693BF'
hc attr theme.active.outer_color '#240054'
hc attr theme.background_color '#141414'

hc set window_gap 4
hc set frame_padding 4
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 1

# rules
hc unrule -F
hc rule focus=on
# hc rule class=Gmrun pseudotile=on focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class='logout-dialog' pseudotile=on focus=on

# nice tree styles:
#herbstclient set tree_style '╾│ ├└╼─┐'
herbstclient set tree_style '╾│ ├╰╼─╮'
# herbstclient set tree_style '*| +`>-.'
#herbstclient set tree_style '*| +`-->'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=/home/rick/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" & # $monitor &
done

hc unlock
